// import-legend.js
// One-time script — imports the master legend JSON into Supabase device_types table.
// Run from your take-off repo root:
//   node import-legend.js
// ─────────────────────────────────────────────────────────────────

import { createClient } from "@supabase/supabase-js";

const SUPABASE_URL      = process.env.SUPABASE_URL;
const SUPABASE_SERVICE_KEY = process.env.SUPABASE_SERVICE_KEY; // set in terminal before running
const PROJECT_ID        = 1;

if (!SUPABASE_URL || !SUPABASE_SERVICE_KEY) {
  console.error("ERROR: set SUPABASE_URL and SUPABASE_SERVICE_KEY env vars before running");
  console.error("  export SUPABASE_URL=https://<project-ref>.supabase.co");
  console.error("  export SUPABASE_SERVICE_KEY=your_service_role_key_here");
  process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY);

const devices = [
  { legend_id:"DEV_001", name:"Outlet, Combination Telephone/Data Communication", description:"Solid black downward-pointing equilateral triangle (▼). Approximately 8–10 mm on drawing. No outline border — fully filled. May have superscript letter X and Z above for port count and conduit flag. Appears at wall or floor jack locations.", category:"telecom_outlet", discipline:"telecom", notes:"Primary data/voice wall outlet. Distinguish from Remote Dictating Outlet (DEV_018) which is a right-pointing filled arrow, not downward." },
  { legend_id:"DEV_002", name:"Outlet Telephone (wall plate)", description:"Small solid downward-pointing triangle (▼) paired with superscript letters X (port count) and Z (conduit flag) positioned above-left. May also show Y for conduit installed. Very similar to DEV_001 but always appears with X–Y or X–Z annotation labels directly adjacent. Blank=new conduit; P=pole/pedestal; F=furniture; C=outlet with new conduit. J=jack type, W=wall type, A=analog port.", category:"telecom_outlet", discipline:"telecom", notes:"Distinguish from DEV_001 by the X/Y/Z letter pair annotation. Both use a filled downward triangle but DEV_002 always has the X–Y subscript pair." },
  { legend_id:"DEV_003", name:"Outlet Data or VoIP Telephone (floor box variant)", description:"Two variants: (a) solid downward triangle ▼ with X–Y labels above — wall-mount variant; (b) same triangle inside or beside a small open square indicating floor-box mounting. Superscript Y indicates conduit. Floor box version has visible square boundary around or adjacent to the triangle.", category:"telecom_outlet", discipline:"telecom", notes:"Floor-box variant distinguishable by the open square border surrounding the triangle. Wall variant nearly identical to DEV_002 — look for floor box square." },
  { legend_id:"DEV_004", name:"Outlet — Audio/Video", description:"Small open square or rectangle with superscript letter M (mount type) above and subscript V below, or A=Audio / V=Video designator. Appears as a plain rectangle with letter designator.", category:"av_outlet", discipline:"telecom", notes:"A=Audio, V=Video, I=Intercom per legend text." },
  { legend_id:"DEV_005", name:"Speaker, Ceiling Mounted", description:"Small hollow circle (ring outline, white fill) with superscript letter S (type from schedule) and superscript X above. Approximately 8 mm diameter. No internal markings. Circle outline only.", category:"audio", discipline:"telecom", notes:"Distinguish from Telecommunications Manhole (DEV_023) which is larger and labeled C. Distinguish from DEV_006 (wall speaker) which is a square not a circle." },
  { legend_id:"DEV_006", name:"Speaker, Wall Mounted", description:"Small open square (hollow, white fill, black outline) with superscript letter S and X above. Approximately 8 mm square. No internal markings. MTD 7'-6\" AFF unless noted.", category:"audio", discipline:"telecom", notes:"Distinguish from DEV_005 (ceiling speaker = circle) — wall speaker is a square." },
  { legend_id:"DEV_007", name:"Radio Channel Selector Facilities", description:"Rectangle outline (horizontal, landscape orientation) with letter R and a short horizontal line extending from its right side. Approximately 10–12 mm wide. MTD 4'-6\" AFF.", category:"audio", discipline:"telecom", notes:"The horizontal extending line distinguishes it from plain rectangles." },
  { legend_id:"DEV_008", name:"Speaker Program Selector Switch and Volume Control", description:"Rectangle outline with letter R inside and subscript M below. Approximately 10–12 mm wide. MTD 4'-6\" AFF.", category:"audio", discipline:"telecom", notes:"Nearly identical to DEV_007 — distinguish by M subscript and absence of extending line." },
  { legend_id:"DEV_009", name:"Outlet Television / CCTV Monitor", description:"Rectangle (open, black outline) with superscript M above and subscript V below. Blank=4 11/16\" antenna outlet box; C=Camera (CCTV System) MTD 18\" AFF; M=Monitor (CCTV System).", category:"av_outlet", discipline:"telecom", notes:"C suffix = CCTV camera output location. M suffix = CCTV monitor location." },
  { legend_id:"DEV_010", name:"Nurses Call Master Station (NCS)", description:"Rectangle (open outline) with text label 'NCS' centered inside. Horizontal rectangle approximately 12 mm wide. Label is all-caps.", category:"nurse_call", discipline:"telecom", notes:"Label NCS is definitive. Mounted on nurses counter top unless noted." },
  { legend_id:"DEV_011", name:"Nurse Call Terminal Cabinet (NCT)", description:"Rectangle (open outline) with text label 'NCT' centered inside. Similar size to NCS. Label is all-caps.", category:"nurse_call", discipline:"telecom", notes:"Label NCT is definitive. Distinguish from NCS (DEV_010) and N2 (DEV_012) by label text." },
  { legend_id:"DEV_012", name:"Nurse Call Station", description:"Rectangle (open outline) with letter 'N' and subscript numeral '2' inside. May have suffix letters: 2=duplicate/master, D=duty station, E=shower/toilet, P=psychiatric corridor, S=audio visual mall, U=utility call, 3=3-button emergency.", category:"nurse_call", discipline:"telecom", notes:"The subscript number '2' is key. Distinguish from NCS/NCT by single-letter N with numeral." },
  { legend_id:"DEV_013", name:"Wireless Access Point (WAP)", description:"Rectangle (open outline) with text label 'WAP' inside and superscript letter X to the right of the box. Approximately 12 mm wide. S=Staff, G=Guest.", category:"network", discipline:"telecom", notes:"WAP label inside rectangle is definitive. X suffix indicates type (S=staff, G=guest)." },
  { legend_id:"DEV_014", name:"Nurse Call Station (Dome Light Variant)", description:"Small hollow circle (ring outline) with numeral '2' above and subscript letter N below. 2=nurse call dome light quantity above door; D=corridor dome light; I=auxiliary intersectional dome light.", category:"nurse_call", discipline:"telecom", notes:"Circle shape distinguishes from rectangular nurse call stations. Numeral above circle indicates dome light count." },
  { legend_id:"DEV_015", name:"Telephone Terminal Cabinet", description:"Solid black filled rectangle (long horizontal bar, fully black/filled). Approximately 15–20 mm wide, 4–5 mm tall. No label text — distinguished by solid fill. Primary IDF/MDF demarcation device.", category:"telecom_infrastructure", discipline:"telecom", notes:"Solid-fill (all black) bar distinguishes from all other hollow/outline rectangles. Main backbone device and likely the demarcation reference point." },
  { legend_id:"DEV_016", name:"Telephone Backboard (Wall Mounted)", description:"Rectangle (open outline) with text label 'TTB' centered inside. Horizontal rectangle, outline only, no fill. Label is all-caps TTB.", category:"telecom_infrastructure", discipline:"telecom", notes:"TTB label is definitive. May serve as secondary demarcation or IDF location." },
  { legend_id:"DEV_017", name:"3-Pole Twist-Lock Receptacle for Microphone", description:"Small rectangle/box with capital letter M above and subscript R inside or below. Superscript M positioned at top-left. MTD 4'-6\" AFF.", category:"audio", discipline:"telecom", notes:"M with subscript R combination is distinctive. Do not confuse with monitor symbols." },
  { legend_id:"DEV_018", name:"Remote Dictating Outlet", description:"Solid black right-pointing filled triangle (play-button shape ▶). Approximately 8 mm wide. Fully filled, no outline. MTD 1'-6\" AFF unless noted.", category:"av_outlet", discipline:"telecom", notes:"Right-pointing arrow/triangle distinguishes from DEV_001 (downward triangle). Both are solid filled." },
  { legend_id:"DEV_019", name:"Intercom Station", description:"Open rectangle (outline only, no fill, no label text inside). Approximately 10 mm wide x 8 mm tall. Plain horizontal rectangle with no internal markings.", category:"intercom", discipline:"telecom", notes:"Plain unlabeled rectangle — distinguish from intercom staff station (DEV_020) which has S subscript." },
  { legend_id:"DEV_020", name:"Intercom Staff Station", description:"Open rectangle (outline only) with subscript letter 'S' below or at bottom-right corner. Same size as DEV_019. The S subscript is the only distinguishing feature.", category:"intercom", discipline:"telecom", notes:"Identical to DEV_019 except for the S subscript. Look carefully for the small S below the rectangle." },
  { legend_id:"DEV_021", name:"Power/Data Pole", description:"Small circle (outline) with text 'PD' centered inside. Approximately 8 mm diameter. Letters PD inside hollow circle.", category:"power_data", discipline:"telecom", notes:"PD inside circle is definitive. Distinguish from Fiber Optic Umbilical (DEV_022) which has U inside circle." },
  { legend_id:"DEV_022", name:"Fiber Optic Umbilical Cable", description:"Small circle (outline) with letter 'U' centered inside. Approximately 8 mm diameter. Letter U inside hollow circle.", category:"fiber", discipline:"telecom", notes:"U inside circle is definitive. Distinguish from PD (DEV_021) by letter U vs PD." },
  { legend_id:"DEV_023", name:"Telecommunications Manhole", description:"Medium circle (outline ring, no fill) with no letter inside. Larger than speaker/dome symbols — approximately 12–15 mm diameter. Plain circle outline only.", category:"osp", discipline:"osp", notes:"Larger plain circle — distinguish from ceiling speaker (DEV_005, has S superscript) and nurse call dome light (DEV_014, has numeral above)." },
  { legend_id:"DEV_025", name:"Audio Device (DIV 28)", description:"Circle with internal cross/plus forming four quadrants (⊕ symbol), with superscript letter M above and subscript T below. Approximately 10 mm diameter. The cross divides the circle into 4 equal sectors. Mount type: C=ceiling, D=desk, F=flush, H=hidden, M=mullion, P=pedestal, R=rack, S=surface, W=wall.", category:"audio", discipline:"security", notes:"Crosshair circle (⊕) is distinctive. Sub-types: B=Bell, C=Chime, H=Horn, K=Klaxon, L=Listen-In, M=Microphone, S=Sounder, Z=Buzzer." },
  { legend_id:"DEV_026", name:"Bi-Static Beam Sensor", description:"Rectangle outline with diagonal line running corner-to-corner (like a box with a slash), with superscript F and T above, and M above. Approximately 10 mm wide. Functions: I=Infrared, M=Microwave, RX=Receive, TX=Transmit.", category:"sensor", discipline:"security", notes:"The diagonal line through the rectangle is the key distinguishing feature vs plain rectangle devices." },
  { legend_id:"DEV_027", name:"Biometrics Access Control Device", description:"Rectangle outline with a check mark or tick symbol inside, with superscript M and subscript T labels. Approximately 10 mm wide. F=Finger Print, H=Hand Geometry, I=Eye Iris, R=Eye Retina, V=Voice.", category:"access_control", discipline:"security", notes:"Internal check/tick mark distinguishes from plain card reader rectangles." },
  { legend_id:"DEV_028", name:"Card Access Reader", description:"Plain horizontal rectangle outline (no internal markings), with superscript M above and subscript T below. Approximately 10–12 mm wide x 6–8 mm tall. Mount types: C=ceiling, D=desk, F=flush, H=hidden, M=mullion, P=pedestal, R=rack, S=surface, W=wall. Sub-types: B=Barcode, F=Elevator Floor Call, M=Mag Strip, P=Proximity, T=Token.", category:"access_control", discipline:"security", notes:"Plain rectangle — distinguish from Card Reader with Keypad (DEV_029, has dot grid) and Card Reader with T&A (DEV_030, has clock face)." },
  { legend_id:"DEV_029", name:"Card Reader with Keypad", description:"Rectangle outline with internal dot grid pattern (representing keypad buttons), with superscript M above and subscript T below. Grid of dots (3x4 or similar) fills most of the rectangle interior. Approximately 10 mm wide.", category:"access_control", discipline:"security", notes:"Internal dot/grid pattern is definitive. Distinguish from plain card reader (DEV_028) and clock-face variant (DEV_030)." },
  { legend_id:"DEV_030", name:"Card Reader with Time and Attendance", description:"Rectangle outline with internal clock face or circular dial symbol, with superscript M above and subscript T below. Circle inside rectangle represents clock/time display. Approximately 10 mm wide.", category:"access_control", discipline:"security", notes:"Circle-inside-rectangle (clock face) is definitive. Distinguish from keypad variant (DEV_029) and plain reader (DEV_028)." },
  { legend_id:"DEV_031", name:"Central Processing Unit", description:"Plain open rectangle (outline only, no fill, no internal markings, no label inside). No M/T superscript/subscript. Larger rectangle than card reader variants. Horizontal orientation.", category:"access_control", discipline:"security", notes:"No superscript M or subscript T — distinguishes from all M/T-labeled device rectangles." },
  { legend_id:"DEV_032", name:"Control Panel", description:"Double-line rectangle (outer and inner border visible, creating a frame-within-frame look), with superscript M above and subscript T below. The inner border is the key distinguishing feature. Sub-types: B=Burglar, D=Door, F=Fire, P=Perimeter.", category:"control_panel", discipline:"security", notes:"Double-border (frame within frame) is definitive. Distinguish from all single-border rectangles." },
  { legend_id:"DEV_033", name:"Electronic Lock", description:"Rectangle outline with a small 'E' or lock symbol in the upper-left corner or interior, with superscript M above and subscript T below. Sub-types: D=Deadbolt, H=Hybrid, L=Latch Set, M=Magnetic, S=Strike.", category:"access_control", discipline:"security", notes:"Lock symbol or 'E' marking inside rectangle. Distinguish from plain card reader (DEV_028)." },
  { legend_id:"DEV_034", name:"Exit Device", description:"Three horizontal parallel lines (≡ symbol), with subscript T below. Approximately 12 mm wide. No rectangle border — just the three parallel lines.", category:"access_control", discipline:"security", notes:"Triple parallel line symbol is unique — no other device uses this form. D=Delayed Egress, E=Electrified, M=Mechanical, X=High Security." },
  { legend_id:"DEV_035", name:"Fiber Optic Module (DIV 28)", description:"Rectangle outline with text '3D' or '3□' label inside and superscript M above and subscript T below. R=Receiver-Transceiver, TX=Transmitter.", category:"telecom_infrastructure", discipline:"security", notes:"3D label inside rectangle is distinctive." },
  { legend_id:"DEV_036", name:"Field Panel", description:"Larger rectangle outline (taller/bigger than card reader rectangles) with superscript M above and subscript T below. Interior has horizontal lines suggesting a panel with zones. A=Alarm, C=Card Reader. Approximately 14 mm wide x 10 mm tall.", category:"control_panel", discipline:"security", notes:"Larger size and horizontal internal lines distinguish from smaller device rectangles." },
  { legend_id:"DEV_037", name:"Glass Breakage Sensor", description:"Square with X crossing both diagonals (⊠), with superscript M above and subscript T below. Approximately 8 mm square. Both diagonals crossed. Sub-types: A=Audio, S=Shock.", category:"sensor", discipline:"security", notes:"Double-diagonal X-through-square (⊠) is distinctive. Distinguish from Security Screen with Alarm (DEV_056) which has T subscript only." },
  { legend_id:"DEV_038", name:"Intercom (DIV 28)", description:"Circle with internal crosshair AND grid dots (telephone/intercom keypad representation), with superscript M above and subscript T below. May have grid pattern inside circle instead of plain quadrant cross. M=Master, S=Substation.", category:"intercom", discipline:"security", notes:"Circle with grid (keypad dots inside circle) distinguishes from pure crosshair Audio Device (DEV_025)." },
  { legend_id:"DEV_039", name:"Keyboard (Security)", description:"Two solid horizontal parallel lines (double-line). No rectangle border, no M/T labels. Approximately 15 mm wide x 3 mm tall. Appears as two thin parallel horizontal bars.", category:"security", discipline:"security", notes:"Flat double-line (no box) is unique. Distinguish from Exit Device (DEV_034) which has three lines with T subscript." },
  { legend_id:"DEV_040", name:"Keypad Device", description:"Rectangle outline with internal dot grid (keypad buttons pattern), with superscript M above and subscript T below. Very similar to DEV_029 (Card Reader with Keypad).", category:"security", discipline:"security", notes:"Keypad dots inside rectangle. Discipline context (security vs access control) helps differentiate from DEV_029." },
  { legend_id:"DEV_041", name:"Monitor", description:"Rectangle outline with a diagonal line from lower-left to upper-right, with superscript M above and subscript T below. D=Data, G=Graphic, M=Multiscreen, V=Video.", category:"security", discipline:"security", notes:"Single diagonal line inside rectangle is distinctive." },
  { legend_id:"DEV_042", name:"Motion Detector", description:"Triangle (wedge shape, pointing upward) outline with superscript M above and subscript T below. Approximately 10 mm base. D=Dual Technology, IR=Infrared, M=Microwave, U=Ultrasonic, X=Request-for-Exit.", category:"sensor", discipline:"security", notes:"Upward-pointing triangle distinguishes from all rectangular devices. Distinct from downward triangle data outlets (DEV_001/002) which point down and are solid-filled." },
  { legend_id:"DEV_043", name:"Push Button", description:"Rectangle outline with a small filled circle or button symbol inside lower portion, with superscript M above and subscript T below. B=Bell Push, D=Duress, P=Panic, R=Door Release, X=Request-for-Exit.", category:"security", discipline:"security", notes:"Small circle inside rectangle (button) is distinctive. Distinguish from plain card reader (DEV_028) by internal circle." },
  { legend_id:"DEV_044", name:"Recorder", description:"Rectangle outline with two small circles inside (representing tape reels or recording heads), with superscript M above and subscript T below. A=Audio, D=Digital, V=Video.", category:"security", discipline:"security", notes:"Two circles inside rectangle (reel pattern) is distinctive." },
  { legend_id:"DEV_045", name:"Security Access, Annunciator Panel", description:"Rectangle outline with text label 'AP' inside. All-caps label. Approximately 12 mm wide. Open rectangle, no fill.", category:"security", discipline:"security", notes:"AP label inside rectangle is definitive." },
  { legend_id:"DEV_046", name:"Security Access, Buzzer", description:"Small square/rectangle outline with a short upward-pointing line or arrow at top center. Approximately 6–8 mm wide. MTD 1'-6\" AFF unless noted.", category:"security", discipline:"security", notes:"Upward arrow/line above rectangle top edge is distinctive." },
  { legend_id:"DEV_047", name:"Security Access, Control Unit with CCTV Camera", description:"Square outline with X crossing both diagonals (⊠) AND a circle or camera element combined. Square with X plus secondary camera indicator.", category:"security", discipline:"security", notes:"X-through-square with camera element. Distinguish from Glass Breakage Sensor (DEV_037) which is M/T labeled." },
  { legend_id:"DEV_048", name:"Security Access, Generic", description:"Plain letter X (crosshatch of two diagonal lines, no border box). Just the X character. Type indicated by schedule or legend.", category:"security", discipline:"security", notes:"Standalone X with no enclosing box distinguishes from ⊠ (X-in-box) symbols." },
  { legend_id:"DEV_049", name:"Security Access, Horn or Siren", description:"Small rectangle outline with a right-pointing triangle/wedge attached to its right side (like a speaker cone symbol). Approximately 10 mm wide overall.", category:"security", discipline:"security", notes:"Rectangle with attached cone/triangle on right side." },
  { legend_id:"DEV_050", name:"Security Access, Outdoor Microwave Transmission Unit", description:"Rectangle outline (taller vertical rectangle or standard horizontal rectangle with antenna marks). Plain rectangle similar to control panels.", category:"sensor", discipline:"security", notes:"Medium confidence on visual — closely resembles other plain rectangles. Context/label on drawing will confirm." },
  { legend_id:"DEV_051", name:"Security Access, Panic Alarm", description:"Small square outline (approximately 6–8 mm). Plain square, no internal markings, no M/T labels. Smaller than most other device symbols.", category:"security", discipline:"security", notes:"Small plain square with no labels. Distinguish from larger rectangles by size." },
  { legend_id:"DEV_052", name:"Security Access, Video Camera with Lens (PTZ)", description:"Camera dome or body shape: circle (dome) with a mounting base/bracket below it, and optional lens cone extending from front. M=Motion Detector, PZ=Pan-Tilt-Zoom, PTZ=Pan-Tilt-Zoom.", category:"camera", discipline:"security", notes:"Camera shape (dome with bracket/lens) is unique among all symbols." },
  { legend_id:"DEV_053", name:"Security Access, Panning Camera", description:"Large circle outline (360° arc/ring) approximately 14–16 mm diameter, with superscript letter C above. Represents the full panning sweep. C=Ceiling Mounted.", category:"camera", discipline:"security", notes:"Large circle with C superscript. Larger than ceiling speaker (DEV_005). Represents full 360° pan capable camera." },
  { legend_id:"DEV_054", name:"Security Access, Video Camera with Lens, Angle of View", description:"Rectangle or camera body outline with a 40° angle indicator (two lines fanning out forming a V or sector shape). Approximately 10–12 mm wide with angle sector shown.", category:"camera", discipline:"security", notes:"Angle sector (fan of view lines at ~40°) is distinctive. Shows camera field of view." },
  { legend_id:"DEV_055", name:"Security Access, Volumetric Sensor", description:"Diamond shape outline (rotated square, 45°), approximately 10 mm diagonal. Open outline, white fill. No internal markings.", category:"sensor", discipline:"security", notes:"Diamond/rhombus shape is unique — no other DIV 28 symbol uses this form." },
  { legend_id:"DEV_056", name:"Security Screen with Alarm", description:"Square outline with X through both diagonals (⊠), with subscript T below. B=Blind, S=Shade technology type. Approximately 8 mm square.", category:"sensor", discipline:"security", notes:"X-through-square with T subscript. Similar to Glass Breakage Sensor (DEV_037) but with T subscript only (no M superscript)." },
  { legend_id:"DEV_057", name:"Security Window Screen", description:"Rectangle outline (wider than tall) with subscript T below. Plain rectangle, no internal X. B=Blind technology.", category:"sensor", discipline:"security", notes:"Plain rectangle with T subscript only (no M superscript)." },
  { legend_id:"DEV_058", name:"Video Control Keyboard", description:"Rectangle outline with internal horizontal and vertical grid lines forming multiple cells. Approximately 12 mm wide. Grid lines inside rectangle create a keyboard matrix appearance.", category:"security", discipline:"security", notes:"Internal grid (multiple rows and columns of cells) distinguishes from single-dot keypad variants." },
  { legend_id:"DEV_059", name:"Video Motion Detector", description:"Small plain square or rectangle outline, no internal markings, no M/T labels, no text inside. Very small — approximately 6 mm square. Plain open box.", category:"sensor", discipline:"security", notes:"Tiny plain box with no labels." },
  { legend_id:"DEV_060", name:"Security Access, Sensor, Buried Vehicular", description:"Horizontal rectangle outline (wider than tall), no internal markings, no M/T labels. Approximately 12 mm wide x 4 mm tall. Flat and wide profile.", category:"sensor", discipline:"security", notes:"Wide flat rectangle — aspect ratio more horizontal than other device rectangles." },
  { legend_id:"DEV_061", name:"Security Access, Switch, Balanced Magnetic Control", description:"Circle outline with a horizontal line through the center (⊖ symbol). Approximately 8 mm diameter.", category:"sensor", discipline:"security", notes:"Circle with horizontal center line (⊖) is unique. Distinguish from plain circles by the horizontal line." },
  { legend_id:"DEV_062", name:"Security Access, Telephone Handset", description:"Square outline with internal handset/telephone receiver symbol (curved shape representing phone handset). Approximately 8–10 mm square.", category:"security", discipline:"security", notes:"Handset curve inside square is distinctive." },
  { legend_id:"DEV_063", name:"Code One Control and Alarm Station (NIP)", description:"Rectangle outline with text label 'NIP' inside. All-caps. Open rectangle. MTD 5'-0\" AFF unless noted.", category:"nurse_call", discipline:"security", notes:"NIP label is definitive." },
  { legend_id:"DEV_064", name:"Code One Terminal Cabinet (NIT)", description:"Rectangle outline with text label 'NIT' inside. All-caps.", category:"nurse_call", discipline:"security", notes:"NIT label is definitive." },
  { legend_id:"DEV_065", name:"Code One Annunciator Panel (NIA)", description:"Rectangle outline with text label 'NIA' inside. All-caps.", category:"nurse_call", discipline:"security", notes:"NIA label is definitive." },
  { legend_id:"DEV_066", name:"Code One Bedside Station (NI)", description:"Rectangle outline with text label 'NI' inside. All-caps.", category:"nurse_call", discipline:"security", notes:"NI label (two letters only). Distinguish from NIP/NIT/NIA by label length." },
  { legend_id:"DEV_067", name:"Code One Duty Station (NID)", description:"Rectangle outline with text label 'NID' inside. All-caps. MTD 5'-0\" AFF unless noted.", category:"nurse_call", discipline:"security", notes:"NID label is definitive." },
  { legend_id:"DEV_068", name:"Alarm, Check Valve", description:"Diagonal slash line with a small circle at the end (∕○ pattern). Approximately 10 mm long. No rectangle border.", category:"fire_alarm", discipline:"security", notes:"Slash-plus-circle combination is unique to this symbol." },
  { legend_id:"DEV_069", name:"Alarm, Fire Communicator", description:"Rectangle outline with label 'FAC' inside. All-caps.", category:"fire_alarm", discipline:"security", notes:"FAC label inside rectangle is definitive." },
  { legend_id:"DEV_070", name:"Alarm, Fire Panel (FACC/FACP/MFACP/FAAP)", description:"Rectangle outline with label 'FACE' or multi-line text inside identifying panel type. FACC=Central Console, FACP=Control Panel, MFACP=Master Control Panel, FAAP=Annunciator Panel.", category:"fire_alarm", discipline:"security", notes:"FACE/FACC/FACP/MFACP label inside rectangle." },
  { legend_id:"DEV_071", name:"Alarm, Fire (Batteries/Charger/Recorder)", description:"Rectangle outline with label 'BATT' inside. BATT=Batteries, CHR=Charger, FAR=Recorder.", category:"fire_alarm", discipline:"security", notes:"BATT label inside rectangle." },
  { legend_id:"DEV_072", name:"Alarm, Fire Valve Supervisory Switch", description:"Rectangle outline with label 'DSV' inside.", category:"fire_alarm", discipline:"security", notes:"DSV label inside rectangle is definitive." },
  { legend_id:"DEV_073", name:"Alarm, Fire Terminal Cabinet", description:"Rectangle outline with label 'FATC' inside.", category:"fire_alarm", discipline:"security", notes:"FATC label is definitive." },
  { legend_id:"DEV_074", name:"Alarm, Fire Post Indicator Valve", description:"Rectangle outline with label 'PIV' inside.", category:"fire_alarm", discipline:"security", notes:"PIV label is definitive." },
  { legend_id:"DEV_075", name:"Alarm, Transponder or Transmitter", description:"Rectangle outline with label 'FTR' inside.", category:"fire_alarm", discipline:"security", notes:"FTR label is definitive." },
  { legend_id:"DEV_076", name:"Alarm, Fire Manual Pull Station", description:"Small open square outline with letter 'P' subscript or beside it (□P). Plain small box with P indicator. No fill.", category:"fire_alarm", discipline:"security", notes:"Small box with P is distinctive from all rectangle-panel symbols." },
  { legend_id:"DEV_077", name:"Alarm, Gong", description:"Bell or arc shape (curved open arc or tilde ∿). Approximately 8–10 mm wide. No rectangle border.", category:"fire_alarm", discipline:"security", notes:"Bell/arc shape with no rectangular border is distinctive." },
  { legend_id:"DEV_078", name:"Alarm, Horn/Light Assembly with Chime (C)", description:"Square with X through both diagonals (⊠) with superscript C at upper-right corner. Approximately 8 mm square.", category:"fire_alarm", discipline:"security", notes:"X-in-square with C superscript. Distinguish from DEV_079 (no C)." },
  { legend_id:"DEV_079", name:"Alarm, Horn/Light Assembly", description:"Square with X through both diagonals (⊠), no superscript letter. Approximately 8 mm square.", category:"fire_alarm", discipline:"security", notes:"Plain X-in-square, no superscript. Distinguish from DEV_078 (has C superscript)." },
  { legend_id:"DEV_080", name:"Alarm, Horn/Light, Separate Assembly", description:"Square with X (⊠) with a second smaller square or element adjacent, indicating separate mounting of horn and light components.", category:"fire_alarm", discipline:"security", notes:"Separate assembly indicator (two elements) distinguishes from single-unit ⊠." },
  { legend_id:"DEV_081", name:"Alarm, Lamp/Signal/Strobe Light", description:"Plain X (two diagonal crossing lines with no enclosing box). Approximately 8 mm. No border rectangle.", category:"fire_alarm", discipline:"security", notes:"Standalone X with no box. Distinguish from Security Generic X (DEV_048) by fire alarm context." },
  { legend_id:"DEV_082", name:"Alarm, Manual Control", description:"Rectangle with internal horizontal and vertical grid lines (keyboard/grid pattern). In fire alarm context.", category:"fire_alarm", discipline:"security", notes:"Grid-interior rectangle. Context (fire alarm vs security) differentiates from DEV_058." },
  { legend_id:"DEV_083", name:"Alarm, Mini", description:"Small rectangle outline with 'M' label. Smaller than standard horn/light symbols.", category:"fire_alarm", discipline:"security", notes:"Smaller than standard alarm device symbols." },
  { legend_id:"DEV_084", name:"Alarm, Horn (M-Mullion)", description:"Small triangle or wedge outline pointing right with M-Mullion mounting indicator.", category:"fire_alarm", discipline:"security", notes:"Triangle/wedge shape for horn, M-Mullion designation." },
  { legend_id:"DEV_085", name:"Alarm, Sprinkler System Water Flow Bell (WB)", description:"Bell shape outline (traditional bell, wider at bottom) with label 'WB' adjacent. Approximately 10 mm tall.", category:"fire_alarm", discipline:"security", notes:"Bell shape with WB label. Distinguish from Alarm Gong (DEV_077) by bell vs arc shape and WB label." },
  { legend_id:"DEV_086", name:"Alarm, Voice Communication Panel", description:"Circle outline with 'CP' label inside or adjacent. Approximately 10 mm diameter.", category:"fire_alarm", discipline:"security", notes:"Circle with CP label. Distinguish from plain circles by CP text." },
  { legend_id:"DEV_087", name:"Alarm, Tamper Switch", description:"Gear/sunburst circle outline (circle with radiating short spokes around perimeter). Approximately 10 mm diameter.", category:"fire_alarm", discipline:"security", notes:"Gear/radiating-spoke circle is unique among all symbols." },
  { legend_id:"DEV_088", name:"Detection, Gas", description:"Solid or outlined circle (disk shape), approximately 8–10 mm diameter. No internal markings. Plain solid or bold-outline circle.", category:"detector", discipline:"security", notes:"Plain circle — distinguish from speaker circles and nurse call dome circles by drawing context and absence of superscript letters." },
  { legend_id:"DEV_089", name:"Detection, Smoke Control and Pressure Panel (SCCP)", description:"Rectangle outline with 'SCCP' label inside. All-caps.", category:"detector", discipline:"security", notes:"SCCP label inside rectangle is definitive." },
  { legend_id:"DEV_090", name:"Detection Switch, Abort (EPO)", description:"Small square outline with 'EPO' label or small rectangle.", category:"detector", discipline:"security", notes:"EPO label is definitive." },
  { legend_id:"DEV_091", name:"Detection Switch, Valve Tamper", description:"Diamond outline (rotated square) in fire/detection system context. Approximately 8 mm diagonal.", category:"detector", discipline:"security", notes:"Diamond shape in fire/detection context. Distinguish from Volumetric Sensor (DEV_055) by system context." },
  { legend_id:"DEV_092", name:"Detector, Flame Flicker", description:"Triangle outline (pointing upward, flame shape). Approximately 10 mm tall. Open triangle, no fill.", category:"detector", discipline:"security", notes:"Upward triangle (flame) in fire alarm context. Distinguish from Motion Detector (DEV_042) which has M/T labels." },
  { legend_id:"DEV_093", name:"Detector, Flow Switch", description:"Diamond outline with an arrow or directional mark through it (flow indicator inside diamond). Approximately 8 mm.", category:"detector", discipline:"security", notes:"Diamond with arrow element. Distinguish from plain diamond (DEV_091) by internal arrow." },
  { legend_id:"DEV_094", name:"Detector, Heat (solid)", description:"Filled diamond (solid black rhombus). Approximately 8 mm. Fully black filled.", category:"detector", discipline:"security", notes:"Solid filled diamond is distinctive from all outline-only diamond shapes." },
  { legend_id:"DEV_095", name:"Detector, Heat (with indicator)", description:"Circle outline with internal 'R/T', 'HD', or 'RC' text. Approximately 10 mm diameter. R/T=Combination, F=Fixed Temperature Rise, RC=Rate Compensation, R=Rate of Rise.", category:"detector", discipline:"security", notes:"Circle with R/T or HD text inside is distinctive." },
  { legend_id:"DEV_096", name:"Detector, Smoke (Ionization/Photoelectric)", description:"Circle outline with letter 'H' or blank inside. H=Heat Smoke, I=Ionization Smoke, P=Photoelectric Smoke. Blank=Smoke detector.", category:"detector", discipline:"security", notes:"Plain circle with letter designator. The specific letter inside indicates sub-type." },
  { legend_id:"DEV_097", name:"Detector, Smoke, Duct", description:"Circle outline variant with duct indicator. Approximately 10 mm.", category:"detector", discipline:"security", notes:"Duct detector variant of smoke detector circle." },
  { legend_id:"DEV_098", name:"Detector, Switch Level", description:"Diamond outline with level/switch indicator. Approximately 8 mm.", category:"detector", discipline:"security", notes:"Diamond variant with level indicator." },
  { legend_id:"DEV_099", name:"Fire Alarm Station, Manual Pull", description:"T-bar shape or rectangle with a horizontal pull handle below it. Approximately 8 mm wide x 10 mm tall.", category:"fire_alarm", discipline:"security", notes:"Pull handle bar below box is distinctive from all other fire alarm symbols." },
  { legend_id:"DEV_100", name:"Fire Alarm Line (FA)", description:"Line segment with 'FA' label alongside. Routing line type designator, not a placed device.", category:"fire_alarm", discipline:"security", notes:"Line type, not a placed device. FA label on any line indicates fire alarm circuit." },
  { legend_id:"DEV_101", name:"Electromagnetic Type Door Holder Outlet", description:"Rectangle outline with 'DH' or 'DH□' label. Approximately 10 mm wide.", category:"fire_alarm", discipline:"security", notes:"DH label inside rectangle." },
  { legend_id:"DEV_102", name:"City Fire Alarm Master Station", description:"Square outline with internal markings or asterisk pattern. Approximately 10 mm. MTD 5'-6\" AFF unless noted.", category:"fire_alarm", discipline:"security", notes:"Specific city fire alarm master station. May have internal cross pattern." },
  { legend_id:"DEV_103", name:"Fire Alarm Transmitter (Base Loop)", description:"Circle outline with 'FAT' text inside and '2-4-6' numerals below or adjacent. Approximately 12 mm diameter.", category:"fire_alarm", discipline:"security", notes:"FAT label inside circle with 2-4-6 code is definitive." },
  { legend_id:"DEV_104", name:"Fire Alarm Trouble Transmitter (Base Loop)", description:"Circle outline with 'FAT' text inside and '2-4-6' numerals. Nearly identical to DEV_103 — distinguish by Trouble sub-label.", category:"fire_alarm", discipline:"security", notes:"Nearly identical to DEV_103. Distinguish by Trouble sub-label or slightly different internal text." }
];

async function run() {
  console.log(`Importing ${devices.length} devices into project_id=${PROJECT_ID}…`);

  const rows = devices.map(d => ({
    project_id:  PROJECT_ID,
    legend_id:   d.legend_id,
    name:        d.name,
    description: d.description,
    category:    d.category,
    discipline:  d.discipline,
    notes:       d.notes ?? null
  }));

  const { data, error } = await supabase
    .from("device_types")
    .upsert(rows, { onConflict: "project_id,legend_id" })
    .select("id, legend_id, name");

  if (error) {
    console.error("ERROR:", error.message);
    process.exit(1);
  }

  console.log(`✓ ${data.length} devices upserted successfully`);
  data.forEach(d => console.log(`  ${d.legend_id}  ${d.name}`));
}

run();
