-- Brings this branch to parity with production for tables that were added
-- directly (via SQL editor / API) rather than through a tracked migration:
-- the parts/labor-catalog and wall-calibration pipeline additions.

CREATE TABLE IF NOT EXISTS public.parts_catalogs (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  org_id bigint NOT NULL REFERENCES public.organizations(id),
  name text NOT NULL,
  source_file text,
  created_at timestamptz NOT NULL DEFAULT now(),
  material_margin numeric NOT NULL DEFAULT 0.10
);

CREATE TABLE IF NOT EXISTS public.parts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id bigint NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  part_number text NOT NULL,
  manufacturer text,
  description text,
  category text,
  unit text,
  cost_unit numeric(12,4),
  source text DEFAULT 'REV_10_MASTER_QUOTE',
  updated_at timestamptz DEFAULT now(),
  catalog_id bigint NOT NULL REFERENCES public.parts_catalogs(id),
  active boolean NOT NULL DEFAULT true,
  device_role text,
  UNIQUE (catalog_id, part_number),
  UNIQUE (org_id, part_number, unit)
);

ALTER TABLE public.parts_catalogs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS parts_catalogs_tenant_isolation ON public.parts_catalogs;
CREATE POLICY parts_catalogs_tenant_isolation ON public.parts_catalogs
  USING (org_id = auth_org_id());

ALTER TABLE public.parts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS org_isolation ON public.parts;
CREATE POLICY org_isolation ON public.parts
  USING (org_id = auth_org_id())
  WITH CHECK (org_id = auth_org_id());

CREATE OR REPLACE VIEW public.parts_priced AS
SELECT
  p.id, p.catalog_id, p.org_id, p.part_number, p.manufacturer, p.description,
  p.category, p.device_role, p.unit, p.cost_unit, pc.material_margin,
  round(p.cost_unit / (1 - pc.material_margin), 4) AS sale_unit,
  p.active, p.source, p.updated_at
FROM parts p
JOIN parts_catalogs pc ON pc.id = p.catalog_id;

CREATE TABLE IF NOT EXISTS public.wall_calibrations (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  org_id bigint NOT NULL REFERENCES organizations(id),
  project_id bigint NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  stroke_color jsonb NOT NULL,
  stroke_width double precision NOT NULL,
  score integer NOT NULL,
  runner_up_score integer,
  candidates jsonb NOT NULL DEFAULT '[]',
  candidate_idx integer NOT NULL DEFAULT 0,
  pages_evaluated integer NOT NULL,
  pages_agreeing integer NOT NULL,
  preview_page_id bigint REFERENCES pages(id),
  status text NOT NULL DEFAULT 'suggested'
    CHECK (status IN ('suggested','confirmed','rejected')),
  confirmed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (project_id)
);
CREATE INDEX IF NOT EXISTS idx_wall_calibrations_project ON wall_calibrations(project_id);

CREATE TABLE IF NOT EXISTS public.page_wall_geometry (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  org_id bigint NOT NULL REFERENCES organizations(id),
  page_id bigint NOT NULL UNIQUE REFERENCES pages(id) ON DELETE CASCADE,
  project_id bigint NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  wall_calibration_id bigint REFERENCES wall_calibrations(id),
  walls jsonb NOT NULL,
  doors jsonb NOT NULL DEFAULT '[]',
  tray jsonb NOT NULL DEFAULT '[]',
  extracted_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_page_wall_geometry_project ON page_wall_geometry(project_id);

ALTER TABLE wall_calibrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE page_wall_geometry ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS org_isolation ON wall_calibrations;
CREATE POLICY org_isolation ON wall_calibrations
  FOR ALL TO authenticated
  USING (org_id = auth_org_id())
  WITH CHECK (org_id = auth_org_id());

DROP POLICY IF EXISTS org_isolation ON page_wall_geometry;
CREATE POLICY org_isolation ON page_wall_geometry
  FOR ALL TO authenticated
  USING (org_id = auth_org_id())
  WITH CHECK (org_id = auth_org_id());

CREATE TABLE IF NOT EXISTS public.labor_tasks (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  catalog_id bigint NOT NULL REFERENCES parts_catalogs(id),
  org_id bigint NOT NULL REFERENCES organizations(id),
  task_name text NOT NULL,
  section text,
  device_role text,
  hrs_per_unit numeric,
  setup_hrs numeric,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE labor_tasks ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS labor_tasks_tenant_isolation ON labor_tasks;
CREATE POLICY labor_tasks_tenant_isolation ON labor_tasks
  USING (org_id = auth_org_id());

ALTER TABLE public.device_types ADD COLUMN IF NOT EXISTS labor jsonb NOT NULL DEFAULT '{}'::jsonb;
